version: 0.2
phases:
  pre_build:
    commands:
       - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 137307166466.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "=== Current directory ==="
      - pwd
      - echo "=== All files in source ==="
      - find . -type f
      - docker build -t quiet-shark-jtinka .
      - docker tag quiet-shark-jtinka:latest 137307166466.dkr.ecr.ap-south-1.amazonaws.com/quiet-shark-jtinka:latest
  post_build:
    commands:
     - docker push 137307166466.dkr.ecr.ap-south-1.amazonaws.com/quiet-shark-jtinka:latest
     - printf '[{"name":"%s","imageUri":"%s"}]' "quiet-shark-jtinka" "137307166466.dkr.ecr.ap-south-1.amazonaws.com/quiet-shark-jtinka" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
